### ISSUE TITLE
[⛔ ERROR] Textura no visible de la piedra infestada

### ISSUE THREAD

**Issue by alexandros007** [DorrD/TexturePack#5]
**Descripción del error**
la piedra infestada (con lepisma) se ve de color negro

**Capturas** (opcional)
[Inserte imágenes o vídeos]
![2021-06-21_20 08 39](https://user-images.githubusercontent.com/34277998/122815460-c5015d00-d2d5-11eb-898c-82d8a12516ef.png)

**Información técnica**
 - Minecraft Version: la version es 1.17
 - Versión: 0.7.1

**Nota adicional** (opcional)
[Tu mensaje aquí]

**Comment by Esteor0tip0** [comment]
@alexandros007 Este problema, no lo detecto. ¿Tienes algún mod o algún texture pack colocado por encima de ello?

**Comment by alexandros007** [comment]
no, solo estaba usando optifine

**Comment by Esteor0tip0** [comment]
Por favor, para identificarlo, comparte tu log cuando viste ese incidente.

**Comment by Esteor0tip0** [comment]
¡Perdona! Este error ya lo detecté, en la próxima versión será arreglado. Este ticket lo cerraremos, cuando se encuentre arreglado este error. ¡Gracias por reportar este problema!

**Comment by Esteor0tip0** [comment]
¡Buenas noticias! He lanzado una versión experimental de tu posible solución.
Posiblemente en esa "build" se arregle o no, es una versión experimental que aún no fue lanzada.
Para descargar: [Haz clic aquí](https://github.com/DorrD/TexturePack/blob/gh-pages/Build%20Dev%20Version/DorrD%20Pack%202.zip)

**Recuerdo:** Es una versión experimental, puedes sufrir crasheos o consecuencias. Esta versión, está realizada para la solución a tu error. Por favor, necesitamos tu confirmación cuando lo haga. En caso, que funcione correctamente, ignóralo. Un saludo.

**Comment by alexandros007** [comment]
hola, venía a decir que la build no lo ha arreglado, aparte ha echo que todos los bloques o la mayor parte sean de color negro

**Comment by Esteor0tip0** [comment]
No te preocupes, en la próxima versión, se arreglará.

**Comment by Esteor0tip0** [comment]
¡Buenas noticias @alexandros007 ! La solución ya está en vuestras manos, con la recién actualización.
Novedades: [Descargar](https://github.com/DorrD/TexturePack/releases/tag/0.7.2-build)

Por cierto, aquí ya no podrás comentar más. En caso del mismo problema o nuevos, por favor, comenta. Estaremos pendientes, de atenderte. 😀
